language: java
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services:
  - mysql
before_install:
  - mysql -u intellij --password="intellijPW" 
