language: java
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services:
  - mysql
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('intellijPW') where User='intellij'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u intellij -p123123
  - sudo service mysql restart
  before_script:
- sudo mysql -e 'CREATE DATABASE allenvooreen;'
