language: java
install:
      - mvn -N io.takari:maven:wrapper
      - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
      - oraclejdk8
      - oraclejdk9
      - oraclejdk11
      - openjdk8
      - openjdk10
      - openjdk11